const Discord = require('discord.js');

module.exports = {
    name: 'noobrate',
    description: 'Kinda self explanotory',
    execute(message, args){
        
        const member = message.mentions.members.first();
        const memberTarget = message.mentions.members.first() || message.guild.members.cache.get(args[0]) || message.author;
        const options = [
            `<@${memberTarget.id}> is **1%** noob `,
            `<@${memberTarget.id}> is **2%** noob `,
            `<@${memberTarget.id}> is **3%** noob `,
            `<@${memberTarget.id}> is **4%** noob `,
            `<@${memberTarget.id}> is **5%** noob `,
            `<@${memberTarget.id}> is **6%** noob `,
            `<@${memberTarget.id}> is **7%** noob `,
            `<@${memberTarget.id}> is **8%** noob `,
            `<@${memberTarget.id}> is **9%** noob `,
            `<@${memberTarget.id}> is **10%** noob `,
            `<@${memberTarget.id}> is **11%** noob `,
            `<@${memberTarget.id}> is **12%** noob `,
            `<@${memberTarget.id}> is **13%** noob `,
            `<@${memberTarget.id}> is **14%** noob `, 
            `<@${memberTarget.id}> is **15%** noob `,
            `<@${memberTarget.id}> is **16%** noob `,
            `<@${memberTarget.id}> is **17%** noob `,
            `<@${memberTarget.id}> is **18%** noob `,
            `<@${memberTarget.id}> is **19%** noob `,
            `<@${memberTarget.id}> is **20%** noob `,
            `<@${memberTarget.id}> is **21%** noob `,
            `<@${memberTarget.id}> is **22%** noob `,
            `<@${memberTarget.id}> is **23%** noob `,
            `<@${memberTarget.id}> is **24%** noob `,
            `<@${memberTarget.id}> is **25%** noob `,
            `<@${memberTarget.id}> is **26%** noob `,
            `<@${memberTarget.id}> is **27%** noob `,
            `<@${memberTarget.id}> is **28%** noob `,
            `<@${memberTarget.id}> is **29%** noob `,
            `<@${memberTarget.id}> is **30%** noob `,
            `<@${memberTarget.id}> is **31%** noob `,
            `<@${memberTarget.id}> is **32%** noob `,
            `<@${memberTarget.id}> is **33%** noob `,
            `<@${memberTarget.id}> is **34%** noob `,
            `<@${memberTarget.id}> is **35%** noob `,
            `<@${memberTarget.id}> is **36%** noob `,
            `<@${memberTarget.id}> is **37%** noob `,
            `<@${memberTarget.id}> is **38%** noob `,
            `<@${memberTarget.id}> is **39%** noob `,
            `<@${memberTarget.id}> is **40%** noob `,
            `<@${memberTarget.id}> is **41%** noob `,
            `<@${memberTarget.id}> is **42%** noob `,
            `<@${memberTarget.id}> is **43%** noob `,
            `<@${memberTarget.id}> is **44%** noob `,
            `<@${memberTarget.id}> is **45%** noob `,
            `<@${memberTarget.id}> is **46%** noob `,
            `<@${memberTarget.id}> is **47%** noob `,
            `<@${memberTarget.id}> is **48%** noob `,
            `<@${memberTarget.id}> is **49%** noob `,
            `<@${memberTarget.id}> is **50%** noob `,
            `<@${memberTarget.id}> is **51%** noob `,
            `<@${memberTarget.id}> is **52%** noob `,
            `<@${memberTarget.id}> is **53%** noob `,
            `<@${memberTarget.id}> is **54%** noob `,
            `<@${memberTarget.id}> is **55%** noob `,
            `<@${memberTarget.id}> is **56%** noob `,
            `<@${memberTarget.id}> is **57%** noob `,
            `<@${memberTarget.id}> is **58%** noob `,
            `<@${memberTarget.id}> is **59%** noob `,
            `<@${memberTarget.id}> is **60%** noob `,
            `<@${memberTarget.id}> is **61%** noob `,
            `<@${memberTarget.id}> is **62%** noob `,
            `<@${memberTarget.id}> is **63%** noob `,
            `<@${memberTarget.id}> is **64%** noob `,
            `<@${memberTarget.id}> is **65%** noob `,
            `<@${memberTarget.id}> is **66%** noob `,
            `<@${memberTarget.id}> is **67%** noob `,
            `<@${memberTarget.id}> is **68%** noob `,
            `<@${memberTarget.id}> is **69%** noob `,
            `<@${memberTarget.id}> is **70%** noob `,
            `<@${memberTarget.id}> is **71%** noob `,
            `<@${memberTarget.id}> is **72%** noob `,
            `<@${memberTarget.id}> is **73%** noob `,
            `<@${memberTarget.id}> is **74%** noob `,
            `<@${memberTarget.id}> is **75%** noob `,
            `<@${memberTarget.id}> is **76%** noob `,
            `<@${memberTarget.id}> is **77%** noob `,
            `<@${memberTarget.id}> is **78%** noob `,
            `<@${memberTarget.id}> is **79%** noob `,
            `<@${memberTarget.id}> is **80%** noob `,
            `<@${memberTarget.id}> is **81%** noob `,
            `<@${memberTarget.id}> is **82%** noob `,
            `<@${memberTarget.id}> is **83%** noob `,
            `<@${memberTarget.id}> is **84%** noob `,
            `<@${memberTarget.id}> is **85%** noob `,
            `<@${memberTarget.id}> is **86%** noob `,
            `<@${memberTarget.id}> is **87%** noob `,
            `<@${memberTarget.id}> is **88%** noob `,
            `<@${memberTarget.id}> is **89%** noob `,
            `<@${memberTarget.id}> is **90%** noob `,
            `<@${memberTarget.id}> is **91%** noob `,
            `<@${memberTarget.id}> is **92%** noob `,
            `<@${memberTarget.id}> is **93%** noob `,
            `<@${memberTarget.id}> is **94%** noob `,
            `<@${memberTarget.id}> is **95%** noob `,
            `<@${memberTarget.id}> is **96%** noob `,
            `<@${memberTarget.id}> is **97%** noob `,
            `<@${memberTarget.id}> is **98%** noob `,
            `<@${memberTarget.id}> is **99%** noob `,
            `<@${memberTarget.id}> is **100%** noob `,
            `<@${memberTarget.id}> is **101%** noob `,
            `<@${memberTarget.id}> is **6969%** noob `,
            `<@${memberTarget.id}> is **420%** noob `,
            `<@${memberTarget.id}> is **1000%** noob `,
            `<@${memberTarget.id}> is **1001%** noob `,
            `<@${memberTarget.id}> is not a noob <:pepeok:815779836340600832>`

            ]
        
        const option = options[Math.floor(Math.random() * options.length)]
        const noobEmbed = new Discord.MessageEmbed()
        .setTitle('Noob r8 machine')
        .setColor('RANDOM')
        .setDescription(`\n${option}`);
        message.channel.send(noobEmbed);
    }
}
